# Generated by Django 4.2.5 on 2023-10-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_purchase', models.DurationField(auto_created=True)),
                ('category', models.CharField(choices=[('laptops', 'Laptops'), ('desktops', 'Desktops'), ('phones', 'Phones'), ('accessories', 'Accessories')], default='phones', max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('unit_price', models.FloatField(default=1.0)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sold_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_csv', models.BooleanField(default=False)),
            ],
        ),
    ]
