# Generated by Django 4.2.5 on 2023-10-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='time_of_purchase',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
