# Generated by Django 4.2.5 on 2023-10-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_issue_product_product_model_delete_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='selling_price',
            field=models.FloatField(null=True),
        ),
    ]
