# Generated by Django 4.2.5 on 2023-10-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0005_product_model_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='sold_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
