# Generated by Django 4.2.5 on 2023-10-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0008_product_model_qty_sold_product_model_sold_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='qty_added',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
