# Generated by Django 4.2.5 on 2023-10-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0009_product_model_qty_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='sold_by',
            field=models.CharField(blank=True, help_text='Your Names', max_length=230, null=True),
        ),
        migrations.CreateModel(
            name='Purchase_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.PositiveBigIntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.product_model')),
            ],
        ),
    ]
